on:
  #push:
  pull_request:
  workflow_dispatch:

jobs:
  build:
    name: ${{ matrix.config.os }}
    runs-on: ${{ matrix.config.os }}
    strategy:
      matrix:
        config: [
              {os: ubuntu-latest},
              {os: windows-latest}
        ]
    steps:
      - run: echo 'done'
