on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
      
  second:
    needs: first
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
