on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
      
  pre:
    needs: first
    uses: ./.github/workflows/reusable.yml

  task:
    if: ${{ success() || failure() || cancelled() }}
    needs: [first,pre]
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
