on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: exit 0
  pre:
    needs: first
    runs-on: ubuntu-latest
    steps:
      - run: exit 1

  task:
    needs: pre
    if: ${{ failure() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
