on:
  workflow_dispatch:

jobs:
  first:
    runs-on: ubuntu-latest
    steps:
      - run: exit 1
      
  second:
    needs: first
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
