on:
  workflow_dispatch:

jobs:
  pre:
    uses: ./.github/workflows/reusable.yml

  task:
    if: ${{ success() || failure() || cancelled() }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
