on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest, no-runner]
        ids: [0,1,2]
    steps:
      - run: sleep 30
        shell: bash
