on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        include:
          - num: 0
          - num: 1
          - num: 2
          - num: 3
          - num: 4
    steps:
      - run: |
          if (( ${{ matrix.num }} == 2 )); then
            exit 1
          fi
