on:
  workflow_dispatch:

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Compute matrix
        id: set-matrix
        run: |
          VAL=$(cat test.json | tr -d '\n')
          echo "matrix=$VAL" >> "$GITHUB_OUTPUT"

  build:
    needs:
      - setup
    strategy:
      matrix: ${{ fromJson(needs.setup.outputs.matrix) }}
      fail-fast: false
    name: ${{ matrix.plan.mode.platformIndependent == true && matrix.plan.mode.name || format('{0} / {1}', matrix.plan.platform.name, matrix.plan.mode.name) }}
    runs-on: ubuntu-latest
    steps:
      - run: echo 'done'
