on:
  workflow_dispatch:

jobs:
  job-name:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        num: [0,1,2,3,4]
    steps:
      - run: |
          if [${{ matrix.num }} == 2]; then
            exit 1
          fi
